test_that("Test Plots", {
    formula <- yn~x
    fit_lm <- lm(formula, data=simreg)
    glm_fit <- glm(formula=formula, data=simreg)
    pd <- predict(fit_lm)
    results <- em(fit_lm, latent=3, verbose=T)
    plot(results)
    browser()
    dev.off()
    # plot(results, by="response")
    # dev.off()
    plot(results, by="prob")
    dev.off()
    # plot(results, by="prob.hist")
    # dev.off()
})
