test_that("Test Plots", {
    formula <- yn~x
    fit_lm <- lm(formula, data=simReg)
    glm_fit <- glm(formula=formula, data=simReg)
    pd <- predict(fit_lm)
    results <- em(fit_lm, latent=3, verbose=T)
    plot(results)
    dev.off()
    plot(results, by="response")
    dev.off()
    plot(results, by="prob")
    dev.off()
    plot(results, by="prob.hist")
    dev.off()
})
