# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mix_ll <- function(theta, Y, X, d, latent, family, isLog, constraint) {
    .Call(`_em_mix_ll`, theta, Y, X, d, latent, family, isLog, constraint)
}

pi_ll <- function(alpha, X, d, latent) {
    .Call(`_em_pi_ll`, alpha, X, d, latent)
}

post_pr <- function(theta, pi_m, Y, X, latent, family, constraint) {
    .Call(`_em_post_pr`, theta, pi_m, Y, X, latent, family, constraint)
}

